Repository aws-controllers-k8s/community, pull requests merged in 2020-12, with the labels that each got.

#544 Adding update-api operation in apigatewayv2 e2e test.
  scripts/lib/aws/apigatewayv2.sh
  test/e2e/apigatewayv2/api/e2e.sh
Labels: APIGateway

#580 Fixes for Snapshot failures
  pkg/runtime/reconciler.go
  services/elasticache/pkg/resource/snapshot/custom_update_api.go
  test/e2e/elasticache/snapshot/e2e.sh
Labels: DO NOT MERGE

#575 Generate printer columns for service controller CRDs
  pkg/generate/config/field.go
  pkg/generate/generator.go
  pkg/model/crd.go
  templates/apis/crd.go.tpl
Labels: Sagemaker

#605 refactor: simplify goCodeSetOutputForContainer
  pkg/model/crd.go
Labels: code generator
