Repository aws-controllers-k8s/community, pull requests merged in 2020-09, with the labels that each got.

#275 add github action to auto deploy mkdocs
  .github/workflows/mkdocs-deploy.yml
Labels: documentation, project-management

#258 changing to zap log
  go.mod
  pkg/runtime/config.go
  pkg/runtime/reconciler.go
  test/integration/services/go.sum
Labels: DO NOT MERGE

#271 Handling ValidationException in HTTP API creation & status patching.
  pkg/generate/apigwv2_test.go
  pkg/generate/template.go
  pkg/model/crd.go
  templates/pkg/crd_sdk.go.tpl
Labels: APIGateway

#255 CARM cache implementation
  apis/core/v1alpha1/annotations.go
  pkg/runtime/cache/account.go
  pkg/runtime/cache/account_test.go
  pkg/runtime/cache/cache.go
  pkg/runtime/cache/namespace.go
  pkg/runtime/cache/namespace_test.go
  pkg/runtime/reconciler.go
  pkg/runtime/registry.go
  pkg/runtime/service_controller_test.go
  templates/config/controller/deployment.yaml.tpl
Labels: IAM

#331 apigwv2 developer-preview
  docs/contents/services.md
  pkg/generate/apigwv2_test.go
  pkg/generate/codedeploy_test.go
  pkg/generate/dynamodb_test.go
  pkg/generate/ec2_test.go
  pkg/generate/ecr_test.go
  pkg/generate/elasticache_test.go
  pkg/generate/rds_test.go
  pkg/generate/s3_test.go
  pkg/generate/sns_test.go
  pkg/generate/sqs_test.go
  pkg/generate/template.go
  pkg/generate/testdata/models/apis/rds/0000-00-00/generator.yaml
  pkg/model/crd.go
  scripts/lib/aws_apigwv2_testutil.sh
  scripts/lib/k8s.sh
  scripts/lib/testutil.sh
  services/apigatewayv2/config/controller/deployment.yaml
  services/apigatewayv2/pkg/resource/api/sdk.go
  services/apigatewayv2/pkg/resource/api_mapping/sdk.go
  services/apigatewayv2/pkg/resource/authorizer/sdk.go
  services/apigatewayv2/pkg/resource/deployment/sdk.go
  services/apigatewayv2/pkg/resource/domain_name/sdk.go
  services/apigatewayv2/pkg/resource/integration/sdk.go
  services/apigatewayv2/pkg/resource/integration_response/sdk.go
  services/apigatewayv2/pkg/resource/model/sdk.go
  services/apigatewayv2/pkg/resource/route/sdk.go
  services/apigatewayv2/pkg/resource/route_response/sdk.go
  services/apigatewayv2/pkg/resource/stage/sdk.go
  services/apigatewayv2/pkg/resource/vpc_link/sdk.go
  services/ecr/config/controller/deployment.yaml
  services/elasticache/config/controller/deployment.yaml
  services/s3/config/controller/deployment.yaml
  services/sns/config/controller/deployment.yaml
  templates/pkg/crd_sdk.go.tpl
  test/e2e/apigatewayv2/api/e2e.sh
  test/e2e/apigatewayv2/api/smoke.sh
  test/e2e/apigatewayv2/api_mapping/smoke.sh
  test/e2e/apigatewayv2/authorizer/smoke.sh
  test/e2e/apigatewayv2/deployment/smoke.sh
  test/e2e/apigatewayv2/domain_name/smoke.sh
  test/e2e/apigatewayv2/integration/smoke.sh
  test/e2e/apigatewayv2/integration_response/smoke.sh
  test/e2e/apigatewayv2/model/smoke.sh
  test/e2e/apigatewayv2/route/smoke.sh
  test/e2e/apigatewayv2/route_response/smoke.sh
  test/e2e/apigatewayv2/stage/smoke.sh
  test/e2e/apigatewayv2/vpc_link/smoke.sh
Labels: DO NOT MERGE

#351 fix github action for mkdocs deploy
  .github/workflows/mkdocs-deploy.yml
Labels: DO NOT MERGE, bug, documentation
